### ISSUE TITLE
Wstream scraper fails

### ISSUE THREAD

**Issue by morpheusthewhite** [davidezanella/CatchTheStream#1]
I tried to use this very useful script on a Wstream link but it fails. When launching `python3 main.py <url>` it fails with these errors

```
Treating it as a  wstream  link...
Error getting url
Traceback (most recent call last):
  File "main.py", line 58, in <module>
    subprocess.Popen([vlc_cmd, stream, "--quiet"])
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1637, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

By doing further tests it seems that the `stream` variable is `None`  due to a failed request to the given url, which returns a `<Response [503]>`

**Comment by davidezanella** [comment]
Now it should work again
